### ISSUE TITLE
Wrong message 

### ISSUE THREAD

**Issue by tbrasser** [olegtarasov/esphome-opentherm#20]
https://github.com/olegtarasov/esphome-opentherm/blob/main/components%2Fopentherm%2Fschema.py#L389

**Comment by olegtarasov** [comment]
Why do you think it's wrong?
![CleanShot 2024-11-18 at 22 36 17@2x](https://github.com/user-attachments/assets/29d3d03b-1c25-4889-a271-ecf55ab1b4b4)

**Comment by tbrasser** [comment]
nvm
